### ISSUE TITLE
Fortnite does not go above 30 FPS

### ISSUE THREAD

**Issue by VenusIsJaded** [rushiranpise/Game-Unlocker#10]
I've noticed an issue with Fortnite, it will only go to 30 FPS with no option for 60 in the settings. Obviously, in game, they give an FPS counter and I thought 30 FPS did not seem right because this app was supposed to be spoofing (I assume at least 60 FPS). I used TakoStats and confirmed it to be running at 30 FPS. I made sure Fortnite was selected for the module within LSPosed. I even rebooted my phone and that did not fix the issue

**Comment by rushiranpise** [comment]
I dont play the game, but you can try these

1. Check lsposed logs for the spoof
2. Try to clear app data

**Comment by VenusIsJaded** [comment]
I've done what you suggested. I checked the logs and it does say it spoofed Fortnite with the OnePlus 9R, however, the FPS cap still remains at 30. I've also cleared app data but had no luck

**Comment by rushiranpise** [comment]
Try with this release https://github.com/rushiranpise/Game-Unlocker/suites/18668744432/artifacts/1086110601

**Comment by rushiranpise** [comment]
test
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/13730301/Game.Unlocker.zip)

**Comment by rushiranpise** [comment]
working in 60fps?
