### ISSUE TITLE
does this module include graphic settings? (CODM)

### ISSUE THREAD

**Issue by clickkz** [rushiranpise/Game-Unlocker#11]
I was able to unlock medium + 120fps with this, which normally is capped at low + 120fps. If it does unlock GFX capabilities, then could you add max graphics option? the ROG7, Red magic and S23 Ultra have max gfx.

**Comment by clickkz** [comment]
basically if you can spoof the device to s23 ultra that will unlock all fps and graphic options. or even the rog 7

**Comment by rushiranpise** [comment]
Test this one https://github.com/rushiranpise/Game-Unlocker/suites/18868608658/artifacts/1101174158

clear game app data and check

**Comment by rushiranpise** [comment]
test
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/13730318/Game.Unlocker.zip)

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
