### ISSUE TITLE
Minecraft pe support 

### ISSUE THREAD

**Issue by AntarCrypto** [rushiranpise/Game-Unlocker#15]
Possible to add Minecraft support?
And also any general settings for other games?

**Comment by rushiranpise** [comment]
Even though the main aim of this module is to unlock higher fps,any other features that are device specific are not guaranteed.
It may or maynot work as expected.

For minecraft try this
https://github.com/rushiranpise/Game-Unlocker/suites/18884029546/artifacts/1102361731

Force close and Clear game data

**Comment by AntarCrypto** [comment]
Is it possible to add deferred technical preview?
My device have all the requirements but for some reason it just not showing 😕?

**Comment by rushiranpise** [comment]
probably the game must have xposed protection...

**Comment by rushiranpise** [comment]
try this one https://github.com/rushiranpise/Game-Unlocker/actions/runs/7232980916/artifacts/1119202706

**Comment by rushiranpise** [comment]
test
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/13730310/Game.Unlocker.zip)

**Comment by AntarCrypto** [comment]
> test [Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/13730310/Game.Unlocker.zip)

How to install it?

**Comment by AntarCrypto** [comment]
> test [Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/13730310/Game.Unlocker.zip)

Clash of clans is crashing,I don't think clash of clans is needed cause it's already a lightweight game

**Comment by AntarCrypto** [comment]
![Uploading Screenshot_20231221-090923_Pixel_Launcher.png…]()

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
