### ISSUE TITLE
Please add AOV Vietnam

### ISSUE THREAD

**Issue by hoangtrung99** [rushiranpise/Game-Unlocker#16]
Please add support game AOV server VN. Link Play Store https://play.google.com/store/apps/details?id=com.garena.game.kgvn&hl=vi&gl=US&pli=1

**Comment by minhdanlc124** [comment]
nó hỗ trợ tất cả ứng dụng

**Comment by minhdanlc124** [comment]
> Please add support game AOV server VN. Link Play Store https://play.google.com/store/apps/details?id=com.garena.game.kgvn&hl=vi&gl=US&pli=1

nó hỗ trợ tất cả ứng dụng

**Comment by hoangtrung99** [comment]
@minhdanlc124 tưởng chỉ những game nào tích được trong LSPosed thì mới bật được nhỉ?

**Comment by rushiranpise** [comment]
test this https://github.com/rushiranpise/Game-Unlocker/suites/19032657641/artifacts/1113747307

**Comment by hoangtrung99** [comment]
@rushiranpise 
Thank you very much, I will test it.

**Comment by hoangtrung99** [comment]
@rushiranpise 
I can't find the AOV application in the LSPosed module.

**Comment by rushiranpise** [comment]
try this one https://github.com/rushiranpise/Game-Unlocker/actions/runs/7232980916/artifacts/1119202706

**Comment by hoangtrung99** [comment]
Still can't find AOV in the list

**Comment by rushiranpise** [comment]
test
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/13730320/Game.Unlocker.zip)

**Comment by hoangtrung99** [comment]
Sorry for late reply, i will test it now

**Comment by hoangtrung99** [comment]
It's already in the module list, but it's not working in the game, it seems to be due to the game's configuration.
