### ISSUE TITLE
Not Working on Redmi Note 9 

### ISSUE THREAD

**Issue by ayra43** [rushiranpise/Game-Unlocker#17]
I have installed the module but its not working tho
Upon looking on the log its working spoofing my device but not making any changes in the graphics settings of codm

**Comment by rushiranpise** [comment]
can you clear game data and try?

**Comment by ayra43** [comment]
> can you clear game data and try?

I have already done any method like reinstall the whole game etc

**Comment by rushiranpise** [comment]
tets this https://github.com/rushiranpise/Game-Unlocker/suites/19032657641/artifacts/1113747307

**Comment by ayra43** [comment]
> tets this https://github.com/rushiranpise/Game-Unlocker/suites/19032657641/artifacts/1113747307

Still not working

**Comment by rushiranpise** [comment]
try this one https://github.com/rushiranpise/Game-Unlocker/actions/runs/7232980916/artifacts/1119202706

**Comment by rushiranpise** [comment]
test
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/13730305/Game.Unlocker.zip)

**Comment by ayra43** [comment]
I have an app Pixelify Google photos module isn't that going to conflict on this spoofing module

**Comment by rushiranpise** [comment]
nope

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
