### ISSUE TITLE
Not working for LoL Wildrift.

### ISSUE THREAD

**Issue by Dandy207** [rushiranpise/Game-Unlocker#18]
Hello sorry to make another issue, since i try this module for lol wildrift it doesnt work. and theres no log for spoofing this device. btw if you need the device support here the screenshot i got from the support
![image](https://github.com/rushiranpise/Game-Unlocker/assets/152897876/bc75d99b-20fd-4f5a-be22-e4c260c64954)

**Comment by rushiranpise** [comment]
send game link

**Comment by Dandy207** [comment]
https://play.google.com/store/apps/details?id=com.riotgames.league.wildrift

Here

**Comment by rushiranpise** [comment]
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/13730295/Game.Unlocker.zip)

test

**Comment by Dandy207** [comment]
Already run ver 6.0.0 and spoofed but I think the game is bugged

**Comment by Dandy207** [comment]
![Screenshot_20231221-013559_Shell](https://github.com/rushiranpise/Game-Unlocker/assets/152897876/bd40ecc9-5008-4e96-bbf2-d6f2df6eda34)
![Screenshot_20231221-013510_Wild_Rift](https://github.com/rushiranpise/Game-Unlocker/assets/152897876/96e9c916-8599-40a8-909b-52a73d65218e)

**Comment by rushiranpise** [comment]
can you try to clear game data and try again?

**Comment by Dandy207** [comment]
Wait letme try it

**Comment by Dandy207** [comment]
> can you try to clear game data and try again?

Already try it but still locked 60 fps
![Screenshot_20231221-014522_Settings](https://github.com/rushiranpise/Game-Unlocker/assets/152897876/9daa9af7-0cbb-4f56-a601-1d1a3844d306)
![Screenshot_20231221-014515_Settings](https://github.com/rushiranpise/Game-Unlocker/assets/152897876/80eb5d0d-e1e5-4b98-9825-4164a1783978)

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
