### ISSUE TITLE
Help unlock setting pubg mobile haptics feedback 

### ISSUE THREAD

**Issue by lawza99** [rushiranpise/Game-Unlocker#20]
Xiaomi 11T Pro
![Screenshot_2024-01-12-18-01-22-454_com tencent ig](https://github.com/rushiranpise/Game-Unlocker/assets/147947035/0a3ecddd-924a-482a-afbc-0369cf4349de)
![Screenshot_2024-01-12-18-01-32-166_com tencent ig](https://github.com/rushiranpise/Game-Unlocker/assets/147947035/6ff9cd92-ef80-45a1-be5b-d8d3d7595d63)

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
