### ISSUE TITLE
pubg mobile not working

### ISSUE THREAD

**Issue by qasimkhn** [rushiranpise/Game-Unlocker#22]
on samsung s10 plus i did exactly what u said but cant change graphics to highers settings

**Comment by chimtaobe** [comment]
also encountered the same problem

**Comment by rushiranpise** [comment]
Please check with new release
https://github.com/rushiranpise/Game-Unlocker/releases/tag/6.0.0

Force Stop & Clear game app data after updating

**Comment by qasimkhn** [comment]
i did try above brother but still its not working

**Comment by qasimkhn** [comment]
have you found the solution?

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
