### ISSUE TITLE
issue with v6.0.0 in lsposed

### ISSUE THREAD

**Issue by Bubyldian** [rushiranpise/Game-Unlocker#24]
After installing v6.0.0 from github, lsposed shows available update to older v5.0.0
![Screenshot_2024-02-01-15-32-22-248_com android shell-edit](https://github.com/rushiranpise/Game-Unlocker/assets/97834417/33759d98-273f-456d-a382-90f84c0ac658)

**Comment by rushiranpise** [comment]
ignore it, i have published it on lsposed repo yet.
