### ISSUE TITLE
spoof call of duty mobile garena 

### ISSUE THREAD

**Issue by mkyee** [rushiranpise/Game-Unlocker#26]
this is not an issue , but for currently codm has updated their graphics to MAX and frame rate to 144fps in ULTRA option. 
you may spoof the model as ROG Phone 8 which is AI2401_A

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
