### ISSUE TITLE
Suspended for two weeks using Game Unlocker v5.0.0

### ISSUE THREAD

**Issue by BlackNoir001** [rushiranpise/Game-Unlocker#28]
After 2 months of using Game Unlocker, I've received a 2 week suspension.
![Screenshot_20240319-164431](https://github.com/rushiranpise/Game-Unlocker/assets/130528071/7dfec836-d282-4afc-8880-11070bf1f9a8)

**Comment by CrisCW1990** [comment]
![Screenshot_2024-03-20-23-20-43-230_com activision callofduty shooter](https://github.com/rushiranpise/Game-Unlocker/assets/38779980/8a91bb48-c24d-42f2-aa6d-5b97660202ab)

I have been using this module for a couple of days and just today my CodM account was suspended until March 27

**Comment by CrisCW1990** [comment]
I logged in with my secondary account and a few minutes later they suspended me in the middle of the game.

![Screenshot_2024-03-20-23-32-21-960_com activision callofduty shooter](https://github.com/rushiranpise/Game-Unlocker/assets/38779980/5581c5a3-cfdc-4f75-a7c3-40c45bce467f)

**Comment by dovisp** [comment]
yup. same here :)

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
