### ISSUE TITLE
120 FPS in Call of Duty Mobile all modes

### ISSUE THREAD

**Issue by LeanxModulostk** [rushiranpise/Game-Unlocker#3]
Modify:
• MANUFACTURER "lenovo"
• MODEL "Lenovo TB-9707F"
To unlock 120FPS in all Call of Duty Mobile modes

![Screenshot_20231103-120420_APK_Editor](https://github.com/rushiranpise/Game-Unlocker/assets/105339980/d6758d5a-523f-4da7-9022-9ca534a66b6b)
![Screenshot_20231103-113723_Call_of_Duty](https://github.com/rushiranpise/Game-Unlocker/assets/105339980/56b082d2-2e55-4961-aebe-a421273ab9f7)

[https://t.me/modulostk/4139](https://t.me/modulostk/4139)

**Comment by rushiranpise** [comment]
Thanks for the spoof
