### ISSUE TITLE
asphalt 9

### ISSUE THREAD

**Issue by mbmbhh** [rushiranpise/Game-Unlocker#30]
before, we could change asphalt 9 fps to any fps we want by editing local_profile on root or use dual space apps. like this video: https://youtu.be/1z-p-zktMes?si=x9g7zzZcwjyoq8GG

and on new update we can't.
when we edit the file, it returns to the previous state.
if you can please find a way to fix it. because the game is laggy and not smooth and enjoyable as before even if we spoof to any device.

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)
