### ISSUE TITLE
Add Support

### ISSUE THREAD

**Issue by Riasenpu** [rushiranpise/Game-Unlocker#33]
Add support unlock for Revelation: New World please. https://play.google.com/store/apps/details?id=vng.games.revelation.mobile

**Comment by rushiranpise** [comment]
test with this
[Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)

**Comment by Riasenpu** [comment]
> test with this [Game Unlocker.zip](https://github.com/rushiranpise/Game-Unlocker/files/14808585/Game.Unlocker.zip)

It works. 😱 Much appreciated! Thank you! 😇 This game shows your device model in settings and it says "OnePlus IN 2020"
