### ISSUE TITLE
120 fps com.tencent.tmgp.sgame

### ISSUE THREAD

**Issue by ClayTT** [rushiranpise/Game-Unlocker#4]
Modify:
• MODEL "V2254A"
• DEVICE CODE "PD2254"
![Screenshot_2023-11-04-07-37-46-696_com houvven guise](https://github.com/rushiranpise/Game-Unlocker/assets/49552414/d5c3732f-6498-4acb-8d8e-7eeb1954096c)

**Comment by rushiranpise** [comment]
does it unlocks 120 fps ? And what option do you get with current spoof

**Comment by ClayTT** [comment]
yes

**Comment by ClayTT** [comment]
GUISE

**Comment by rushiranpise** [comment]
Thanks for the spoof
